openapi: 3.0.0
info:
  title: Login API
  version: 1.0.0
  description: API for User and Admin Login
servers:
  - url: http://localhost:3002/auth
    description: Local development server

paths:
  /login:
    post:
      summary: User or Admin login
      description: Allows a user or admin to log in by providing an email and password.
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: "userpassword"
      responses:
        '200':
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        '401':
          description: Invalid email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
